### PR TITLE
SQL setup before migrations

### PR DESCRIPTION
**Pull request by rrsk**

### CODE REVIEW

**Review by mananpal1997 — CHANGES_REQUESTED** [review]
`mysql -u root -p --execute "create database DB_NAME; grant all on DB_NAME.* to DB_USER@localhost identified by 'DB_PASSWORD';"` is for adding database, not table. So, edit that in the readme.

And squash your commits.
Rest is good :+1: :smile:

**Comment by gabru-md** [comment]
@rrsk Please squash your commits so that it can be merged.
Thanks!

**Comment by rrsk** [comment]
Done, thanks for the quick response guys.

**Comment by manrajgrover** [comment]
@mananpal1997 @gabru-md You can now squash commits and merge directly from Github.
https://github.com/blog/2141-squash-your-commits

**Pull request merged**
